# tasks file for wordpress, core
---
- name: Install MySQL client tool
  apt:
    pkg:
    - mysql-client
- name: Remove nginx pid file if it exists
  file:
    path: /workspace/run/nginx.pid
    state: absent
- name: Install the PHP Upstream
  template:
    src: upstream_php.conf
    dest: /etc/nginx/conf.d/upstream_php.conf
    owner: root
    group: root
    mode: '0644'
- name: Start the Frontend
  shell: fe-start
  
