# tasks file for wordpress
---
- include: wp-cli.yml
  tags:
    - configuration
    - wordpress
    - wordpress-wp-cli

- include: core.yml
  tags:
    - configuration
    - wordpress
    - wordpress-core
